version: '3'
services:
  dbbck:
     image: postgres:14.1-alpine
     restart: always
     environment:
       POSTGRES_PASSWORD: vap0987
       POSTGRES_DB: secretnote-prod
     networks:
       - secretnotebck
     volumes:
       - .:/tmp
     ports:
       - 5432:5432
  webbck:
    container_name: secretnote-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
       - '8000:8000'
    env_file:
      - 'env'
    volumes:
      - .:/app
    networks:
      - secretnotebck
    depends_on:
      - dbbck
      - redisbck
  redisbck:
    image: redis:4.0-alpine
    ports:
      - '6379:6379'
    volumes:
      - /usr/local/redis:/data
    networks:
      - secretnotebck
volumes:
  webbck:
  redisbck:
networks:
  secretnotebck:
      name: secretnotebck

